name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation and code quality'
    labels:
      - 'documentation'
exclude-labels:
  - 'dependencies'
  - 'tests'
  - 'infrastructure'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES