name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Database Changes'
    labels:
      - 'database'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation and code quality'
    labels:
      - 'docs'
exclude-labels:
  - 'tests'
  - 'build(deps)'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES