dist: xenial
language: python

python:
- "3.5"
- "3.6"
- "3.7"


install:
- pip install -e .
- pip install -r requirements.txt

# Add latter
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

jobs:
  include:
  - &Tests
    stage: tests
    script: make tests
    cache: false

  - <<: *Tests
    script:
    - make tests
    - bash <(curl -s https://codecov.io/bash)
    python: "3.7"

  - stage: lint
    cache: false
    script: make linters
    python: "3.7"

notifications:
  email: false

  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
  slack:
    rooms:
      - made-ua:XGUkOpb0PsEuqmm0CvHaNfPk#builds
    template:
      - '*%{repository_slug}@%{branch}*<%{compare_url}|#%{commit}> (_%{author}_) - <%{build_url}|Travis CI: Build #%{build_number}>'
      - '*Title:* %{commit_message}'
      - '----------------------------------------------------------------------- '
      - '(`%{build_id}` is `%{result}`) _%{message}_ in `%{elapsed_time}`'
