language: python
python: 3.8


matrix:
  fast_finish: true
  allow_failures:
  - env: FAILURES=ALLOWED

script: skip


jobs:
  include:
    # OK: Tests --------------------------------------------------
    - &Tests
      stage: tests
      name: "Tests (Python 3.8)"
      python: 3.8
      script:
      - make tests

    - <<: *Tests
      name: "Tests (Python 3.7)"
      python: 3.7

    - <<: *Tests
      name: "Tests (Python 3.6)"
      python: 3.6

    - <<: *Tests
      name: "Tests (Python 3.5)"
      python: 3.5


    # OK: Linters ------------------------------------------------
    - stage: lints
      name: "Running Linters"
      python: 3.8
      script: make lints

    # OK: Documentation Checks -----------------------------------
    - stage: docs
      name: "Docs"
      python: 3.8
      script:
      # prebuilding html files
      - pip install -e .
      - make gen-docs
      - pip uninstall deadlinks -yq
      # getting a http server & stable deadlinks
      - go get github.com/CurtisLusmore/ghp
      - pip install deadlinks
      # serving files & running deadlinks checks
      - ghp -root build/dirhtml/ -port 5678 &
      - deadlinks localhost:5678 -n 10 -r 3 --no-progress --no-colors --fiff

    # OK: CodeCoverage -------------------------------------------
    - stage: codecov
      name: "Code Coverage"
      python: 3.8
      if: branch IN (master, develop, develop-deployment)
      script:
      - make coverage
      - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    on_success: never
    on_failure: never
    on_start: never

  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify

  slack:
    rooms:
      - made-ua:XGUkOpb0PsEuqmm0CvHaNfPk#builds
    template:
      - '*%{repository_slug}@%{branch}*<%{compare_url}|#%{commit}> (_%{author}_) - <%{build_url}|Travis CI: Build #%{build_number}>'
      - '*Title:* %{commit_message}'
      - '----------------------------------------------------------------------- '
      - '(`%{build_id}` is `%{result}`) _%{message}_ in `%{elapsed_time}`'
