name: Build & Test

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:

  Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - run: make dev-env
      - run: make pylint-full
      - run: make mypy

  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - run: make docs-build

  Build:
    runs-on: ubuntu-latest
    needs: [ Static-Analysis, Docs ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, 3.10, 3.11 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: make dev-env
      - run: make tests

      - name: codecov.io
        if: matrix.python-version == 3.11
        run: bash <(curl -s https://codecov.io/bash)

