name: Release new Version

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Python Package
    - name: Install dependencies
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel -q
        python setup.py sdist

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}